version: '3'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: user_industry_db_owner
      POSTGRES_PASSWORD: npg_CVd7D6fQqxcH
      POSTGRES_DB: user_industry_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://user_industry_db_owner:npg_CVd7D6fQqxcH@ep-twilight-sky-a85776cs-pooler.eastus2.azure.neon.tech:5432/user_industry_db?schema=public&sslmode=require
      NEXTAUTH_SECRET: apple
      JWT_SECRET: apple
      NODE_ENV: production
    restart: always
    command: >
      sh -c "
        npx prisma migrate deploy && 
        npm run seed && 
        npm start
      "

volumes:
  postgres-data: